"""Add template prompt fields and remove parent-child relationship

Revision ID: e0fae39cd926
Revises: 
Create Date: 2025-10-02 15:01:30.973394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fae39cd926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_template',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )
        batch_op.add_column(sa.Column('configurable_options', sa.JSON(), nullable=True))

    op.execute(sa.text("UPDATE prompts SET is_template = 0"))

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.alter_column('is_template', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_column('configurable_options')
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
